export const levels = [
  { code: "A1", title: "Beginner", description: "Everyday words, basic sentences, and essential communication.", sortOrder: 1 },
  { code: "A2", title: "Elementary", description: "Familiar topics, routine communication, and simple past and future forms.", sortOrder: 2 },
  { code: "B1", title: "Intermediate", description: "Independent communication with connected ideas and practical detail.", sortOrder: 3 },
  { code: "B2", title: "Upper-intermediate", description: "Clear, flexible communication across complex familiar topics.", sortOrder: 4 },
  { code: "C1", title: "Advanced", description: "Precise language for academic, professional, and social contexts.", sortOrder: 5 },
  { code: "C2", title: "Proficient", description: "Nuanced, fluent language with register and stylistic control.", sortOrder: 6 },
];

export const categories = [
  { slug: "everyday-life", name: "Everyday Life" },
  { slug: "family", name: "Family" },
  { slug: "food", name: "Food" },
  { slug: "travel", name: "Travel" },
  { slug: "education", name: "Education" },
  { slug: "work", name: "Work" },
  { slug: "technology", name: "Technology" },
  { slug: "communication", name: "Communication" },
  { slug: "academic-english", name: "Academic English" },
  { slug: "professional-english", name: "Professional English" },
  { slug: "idioms", name: "Idioms" },
  { slug: "advanced-expressions", name: "Advanced Expressions" },
];

export const vocabulary = [
  { level: "A1", category: "everyday-life", word: "morning", partOfSpeech: "noun", definition: "The early part of the day.", arabic: "الصباح", example: "I drink coffee in the morning.", pronunciation: "/ˈmɔːrnɪŋ/", synonyms: ["daybreak"], antonyms: ["night"], family: ["morning"], mistakes: "Do not use 'in the morning' for a specific clock time.", related: ["afternoon"], usefulness: 5 },
  { level: "A1", category: "family", word: "sister", partOfSpeech: "noun", definition: "A girl or woman who has the same parents as you.", arabic: "أخت", example: "My sister lives near our parents.", pronunciation: "/ˈsɪstər/", synonyms: [], antonyms: [], family: ["sisterhood"], mistakes: "Use 'my sister', not 'my a sister'.", related: ["brother", "family"], usefulness: 5 },
  { level: "A2", category: "travel", word: "journey", partOfSpeech: "noun", definition: "A trip from one place to another.", arabic: "رحلة", example: "The journey took three hours.", pronunciation: "/ˈdʒɜːrni/", synonyms: ["trip", "voyage"], antonyms: [], family: ["journey"], mistakes: "A journey is the experience of travelling, not only the destination.", related: ["travel", "route"], usefulness: 5 },
  { level: "A2", category: "food", word: "ingredient", partOfSpeech: "noun", definition: "One of the foods used to make a dish.", arabic: "مكوّن", example: "Fresh herbs are an important ingredient.", pronunciation: "/ɪnˈɡriːdiənt/", synonyms: ["component"], antonyms: [], family: ["ingredient"], mistakes: "Use 'ingredients' for a list of foods.", related: ["recipe", "dish"], usefulness: 4 },
  { level: "B1", category: "education", word: "assignment", partOfSpeech: "noun", definition: "A piece of work given to a learner.", arabic: "واجب", example: "I submitted the assignment before lunch.", pronunciation: "/əˈsaɪnmənt/", synonyms: ["task", "exercise"], antonyms: [], family: ["assign", "assigned"], mistakes: "An assignment is countable: 'an assignment', 'two assignments'.", related: ["deadline", "course"], usefulness: 5 },
  { level: "B1", category: "communication", word: "clarify", partOfSpeech: "verb", definition: "To make an idea easier to understand.", arabic: "يوضّح", example: "Could you clarify the last point?", pronunciation: "/ˈklærɪfaɪ/", synonyms: ["explain", "clear up"], antonyms: ["confuse"], family: ["clarification", "clear"], mistakes: "Use 'clarify something' or 'clarify what you mean'.", related: ["explain", "communication"], usefulness: 5 },
  { level: "B2", category: "work", word: "negotiate", partOfSpeech: "verb", definition: "To discuss in order to reach an agreement.", arabic: "يتفاوض", example: "They negotiated a better contract.", pronunciation: "/nɪˈɡoʊʃieɪt/", synonyms: ["bargain", "discuss"], antonyms: ["impose"], family: ["negotiation", "negotiator"], mistakes: "Negotiate a price, not negotiate about a price in most business contexts.", related: ["contract", "agreement"], usefulness: 5 },
  { level: "B2", category: "technology", word: "reliable", partOfSpeech: "adjective", definition: "Working well and consistently.", arabic: "موثوق", example: "We need a reliable backup system.", pronunciation: "/rɪˈlaɪəbəl/", synonyms: ["dependable", "consistent"], antonyms: ["unreliable"], family: ["rely", "reliability"], mistakes: "Reliable describes a person or thing; 'reliably' describes an action.", related: ["stable", "trust"], usefulness: 4 },
  { level: "C1", category: "academic-english", word: "significant", partOfSpeech: "adjective", definition: "Important or large enough to have an effect.", arabic: "مهم / ذو دلالة", example: "The study found a significant change in reading habits.", pronunciation: "/sɪɡˈnɪfɪkənt/", synonyms: ["substantial", "important"], antonyms: ["minor"], family: ["signify", "significance"], mistakes: "In academic writing, significant can mean important or statistically meaningful; check the context.", related: ["evidence", "impact"], usefulness: 5 },
  { level: "C1", category: "professional-english", word: "implement", partOfSpeech: "verb", definition: "To put a plan or decision into effect.", arabic: "ينفّذ", example: "The team implemented the new policy in June.", pronunciation: "/ˈɪmplɪment/", synonyms: ["apply", "execute"], antonyms: ["abandon"], family: ["implementation"], mistakes: "As a verb, stress the first syllable: IM-plement.", related: ["strategy", "policy"], usefulness: 5 },
  { level: "C2", category: "advanced-expressions", word: "unprecedented", partOfSpeech: "adjective", definition: "Never known or experienced before.", arabic: "غير مسبوق", example: "The crisis created unprecedented demand.", pronunciation: "/ʌnˈpresɪdentɪd/", synonyms: ["unique", "unparalleled"], antonyms: ["ordinary"], family: ["precedent"], mistakes: "Use it for something without a previous example, not simply something unusual.", related: ["exceptional", "novel"], usefulness: 4 },
  { level: "C2", category: "idioms", word: "bear in mind", partOfSpeech: "idiom", definition: "To remember or consider something.", arabic: "يضع في الاعتبار", example: "Bear in mind that the schedule may change.", pronunciation: "/ber ɪn maɪnd/", synonyms: ["remember", "consider"], antonyms: [], family: [], mistakes: "The object follows the phrase: bear something in mind.", related: ["keep in mind", "consider"], usefulness: 4 },
];

export const grammar = [
  { level: "A1", slug: "subject-pronouns", title: "Subject pronouns", category: "sentence-foundations", difficulty: 1, explanation: "Subject pronouns replace the person or thing doing an action.", arabic: "ضمائر الفاعل تحل محل الشخص أو الشيء الذي يقوم بالفعل.", examples: ["I work.", "They live here."], mistakes: ["Do not say 'Me work'; say 'I work'."], prerequisites: [], related: ["verb-to-be"] },
  { level: "A1", slug: "present-simple", title: "Present Simple", category: "verb-tenses", difficulty: 1, explanation: "Use the present simple for routines, facts, and regular events.", arabic: "نستخدم المضارع البسيط للعادات والحقائق والأحداث المتكررة.", examples: ["I study every day.", "She works in a bank."], mistakes: ["Remember -s with he, she, and it: 'She works'."], prerequisites: ["subject-pronouns"], related: ["adverbs-of-frequency"] },
  { level: "A2", slug: "past-simple", title: "Past Simple", category: "verb-tenses", difficulty: 2, explanation: "Use the past simple for completed actions at a finished time.", arabic: "نستخدم الماضي البسيط للأفعال المكتملة في وقت انتهى.", examples: ["I visited Cairo last year.", "They did not arrive on time."], mistakes: ["After did, use the base verb: 'Did you go?'"], prerequisites: ["present-simple"], related: ["past-continuous"] },
  { level: "A2", slug: "first-conditional", title: "First Conditional", category: "conditionals", difficulty: 2, explanation: "Use if + present simple and will + base verb for a likely future result.", arabic: "نستخدم الشرط الأول لنتيجة محتملة في المستقبل.", examples: ["If it rains, we will stay home."], mistakes: ["Do not normally use 'will' directly after if."], prerequisites: ["past-simple"], related: ["second-conditional"] },
  { level: "B1", slug: "present-perfect-vs-past", title: "Present Perfect vs Past Simple", category: "verb-tenses", difficulty: 3, explanation: "The present perfect connects a past action to now; the past simple focuses on a finished past time.", arabic: "يربط المضارع التام الماضي بالحاضر، بينما يركز الماضي البسيط على وقت ماضٍ منتهٍ.", examples: ["I have visited London.", "I visited London in 2022."], mistakes: ["Do not use present perfect with a finished time such as yesterday."], prerequisites: ["past-simple"], related: ["past-perfect"] },
  { level: "B1", slug: "passive-voice", title: "Passive voice", category: "voice", difficulty: 3, explanation: "Use be + past participle when the action or result is more important than the actor.", arabic: "نستخدم المبني للمجهول عندما يكون الفعل أو النتيجة أهم من الفاعل.", examples: ["The report was published in May."], mistakes: ["Keep the tense in the form of be."], prerequisites: ["present-perfect-vs-past"], related: ["advanced-passive"] },
  { level: "B2", slug: "third-conditional", title: "Third Conditional", category: "conditionals", difficulty: 4, explanation: "Use it to imagine a different past and its past result.", arabic: "نستخدمه للتحدث عن ماضٍ مختلف ونتيجته المحتملة.", examples: ["If I had studied, I would have passed."], mistakes: ["Use had + past participle in the if-clause."], prerequisites: ["first-conditional"], related: ["mixed-conditionals"] },
  { level: "B2", slug: "modal-deduction", title: "Modals of deduction", category: "modal-verbs", difficulty: 4, explanation: "Use must, might, could, and can't to express degrees of certainty.", arabic: "نستخدم أفعالاً ناقصة للتعبير عن درجات اليقين والاحتمال.", examples: ["She must be at work.", "They might have missed the train."], mistakes: ["Use have + past participle for deductions about the past."], prerequisites: ["passive-voice"], related: ["advanced-modal-meanings"] },
  { level: "C1", slug: "cleft-sentences", title: "Cleft sentences", category: "emphasis", difficulty: 5, explanation: "Cleft sentences divide information into two clauses to emphasize one part.", arabic: "تقسم جمل التركيز المعلومة إلى جملتين لإبراز جزء معين.", examples: ["What I need is more time.", "It was Sara who solved the problem."], mistakes: ["Choose the cleft pattern that matches the information you want to emphasize."], prerequisites: ["modal-deduction"], related: ["inversion"] },
  { level: "C1", slug: "inversion", title: "Inversion for emphasis", category: "emphasis", difficulty: 5, explanation: "In formal English, negative or limiting adverbs can trigger auxiliary-subject inversion.", arabic: "في الإنجليزية الرسمية قد تؤدي الظروف السلبية أو المحددة إلى عكس ترتيب الفعل المساعد والفاعل.", examples: ["Never have I seen such a view."], mistakes: ["Invert the auxiliary, not the main verb."], prerequisites: ["cleft-sentences"], related: ["advanced-passive"] },
  { level: "C2", slug: "register-and-formality", title: "Register and formality", category: "style", difficulty: 6, explanation: "Advanced speakers choose grammar and structures that fit the relationship, purpose, and setting.", arabic: "يختار المتحدث المتقدم تراكيب تناسب العلاقة والهدف والموقف.", examples: ["We regret to inform you...", "Thanks for letting me know."], mistakes: ["Do not use a formal structure in every casual conversation."], prerequisites: ["inversion"], related: ["nominalisation"] },
  { level: "C2", slug: "ellipsis", title: "Ellipsis and sophisticated clause structure", category: "style", difficulty: 6, explanation: "Ellipsis removes repeated words when the meaning remains clear.", arabic: "تحذف ظاهرة الحذف الكلمات المتكررة عندما يبقى المعنى واضحاً.", examples: ["I can speak English, and my sister can too."], mistakes: ["Only omit words when the remaining structure is unambiguous."], prerequisites: ["register-and-formality"], related: ["cleft-sentences"] },
];

export const pronunciation = [
  { level: "A1", slug: "alphabet-and-letter-names", title: "Alphabet and letter names", sound: "letter names", mouth: "Move slowly and keep the jaw relaxed.", tongue: "Position the tongue for each vowel in the letter name.", voiced: true, explanation: "Learn the names of the English letters and distinguish spelling from pronunciation.", words: ["A", "B", "C"], pairs: [["A", "E"]], mistakes: ["Do not pronounce a letter name as its most common sound."], exercises: [{ prompt: "Listen and repeat the letter name.", target: "A", phonetic: "/eɪ/", type: "listen" }] },
  { level: "A1", slug: "th-voiceless", title: "TH /θ/", sound: "/θ/", mouth: "Place the tip of the tongue lightly between the teeth.", tongue: "Let air pass over the tongue without stopping it.", voiced: false, explanation: "The voiceless TH is used in think, bath, and author.", words: ["think", "three", "bath"], pairs: [["think", "sink"]], mistakes: ["Do not replace /θ/ with /t/ or /s/."], exercises: [{ prompt: "Repeat the minimal pair.", target: "think - sink", phonetic: "/θɪŋk - sɪŋk/", type: "minimal_pair" }] },
  { level: "B1", slug: "r-and-l", title: "R / L", sound: "/r/ and /l/", mouth: "Round slightly for R; keep the sides of the tongue raised for L.", tongue: "The tongue does not touch the roof for English R; it touches behind the teeth for L.", voiced: true, explanation: "Contrast the English R and L sounds in words and connected speech.", words: ["right", "light", "rice", "lice"], pairs: [["right", "light"]], mistakes: ["Avoid adding a vowel before a final R."], exercises: [{ prompt: "Repeat the minimal pair.", target: "right - light", phonetic: "/raɪt - laɪt/", type: "minimal_pair" }] },
  { level: "B2", slug: "word-stress", title: "Word stress", sound: "stress", mouth: "Make the stressed syllable longer, louder, and clearer.", tongue: "Keep unstressed vowels short and relaxed.", voiced: true, explanation: "Stress helps listeners identify words and follow longer speech.", words: ["record", "present", "photograph"], pairs: [["REcord", "reCORD"]], mistakes: ["Do not give every syllable equal weight."], exercises: [{ prompt: "Listen and repeat with the main stress.", target: "photograph", phonetic: "/ˈfoʊtəɡræf/", type: "repeat" }] },
  { level: "C1", slug: "connected-speech", title: "Connected speech and reduction", sound: "linking", mouth: "Move smoothly between words instead of stopping at every boundary.", tongue: "Relax unstressed function words.", voiced: true, explanation: "Natural speech links sounds and reduces unstressed words while keeping the message clear.", words: ["want to", "going to", "next week"], pairs: [["want to", "wanna"]], mistakes: ["Use reductions for natural speech, but keep formal pronunciation when clarity requires it."], exercises: [{ prompt: "Repeat the sentence with smooth linking.", target: "I want to go next week.", phonetic: "/aɪ wɑːnə ɡoʊ nekst wiːk/", type: "repeat" }] },
];

export const sentenceTopics = [
  { level: "A1", slug: "subject-verb-object", title: "Subject + Verb + Object", explanation: "Build a basic sentence with the person, action, and thing affected.", arabic: "كوّن جملة أساسية من الفاعل والفعل والمفعول.", examples: ["I eat apples."], exercises: [{ type: "word_order", prompt: "Arrange: I / apples / eat", options: [], answer: "I eat apples.", explanation: "The usual order is subject + verb + object." }] },
  { level: "A2", slug: "questions-and-negatives", title: "Questions and negatives", explanation: "Use auxiliaries to ask questions and make negative statements.", arabic: "استخدم الأفعال المساعدة لتكوين الأسئلة والنفي.", examples: ["Do you work here?", "I do not work here."], exercises: [{ type: "transformation", prompt: "Make a question: You like tea.", options: [], answer: "Do you like tea?", explanation: "Use do before the subject in a present simple question." }] },
  { level: "B1", slug: "compound-sentences", title: "Compound sentences", explanation: "Join complete ideas with linking words such as because, although, and while.", arabic: "اربط الأفكار الكاملة باستخدام because و although و while.", examples: ["I stayed home because it was raining."], exercises: [{ type: "completion", prompt: "Complete: I stayed home ___ it was raining.", options: ["because", "but"], answer: "because", explanation: "Because introduces the reason." }] },
  { level: "B2", slug: "relative-clauses", title: "Relative clauses", explanation: "Add precise information about a noun with who, which, that, or whose.", arabic: "أضف معلومات دقيقة عن الاسم باستخدام جمل الوصل.", examples: ["The book that you recommended was useful."], exercises: [{ type: "correction", prompt: "Correct: The person which called is my teacher.", options: [], answer: "The person who called is my teacher.", explanation: "Use who for people in this relative clause." }] },
  { level: "C1", slug: "cleft-and-inversion", title: "Cleft sentences and inversion", explanation: "Use advanced structures to focus or give formal emphasis to information.", arabic: "استخدم تراكيب متقدمة للتركيز أو التأكيد الرسمي.", examples: ["What I need is a clear plan."], exercises: [{ type: "transformation", prompt: "Emphasize 'a clear plan': I need a clear plan.", options: [], answer: "What I need is a clear plan.", explanation: "The what-cleft places emphasis on the complement." }] },
  { level: "C2", slug: "academic-clause-structure", title: "Academic and professional clause structure", explanation: "Combine clauses precisely while controlling register, emphasis, and information flow.", arabic: "ادمج الجمل بدقة مع التحكم في الأسلوب والتركيز وتدفق المعلومات.", examples: ["The findings, having been independently verified, warrant further study."], exercises: [{ type: "completion", prompt: "Complete with a participle clause: ___ independently verified, the findings warrant further study.", options: ["Having been", "Being have"], answer: "Having been", explanation: "The perfect passive participle clause shows the verification happened first." }] },
];

export const quizQuestions = [
  { skill: "vocabulary", level: "A2", category: "travel", type: "meaning", prompt: "What does 'journey' mean?", options: ["A trip from one place to another", "A meal", "A school subject"], answer: "A trip from one place to another", explanation: "A journey is a trip from one place to another." },
  { skill: "grammar", level: "A1", category: "verb-tenses", type: "grammar_selection", prompt: "Choose the correct sentence.", options: ["She work in a bank.", "She works in a bank.", "She working in a bank."], answer: "She works in a bank.", explanation: "The third-person singular present simple takes -s." },
  { skill: "sentence_structure", level: "A1", category: "sentence-foundations", type: "word_order", prompt: "Arrange: apples / eat / I", options: [], answer: "I eat apples.", explanation: "English basic word order is subject + verb + object." },
  { skill: "pronunciation", level: "A1", category: "sounds", type: "multiple_choice", prompt: "Which sound is voiceless TH?", options: ["/θ/", "/ð/", "/v/"], answer: "/θ/", explanation: "The /θ/ sound is the voiceless TH in think." },
];